name: 'DigitalOcean kubectl Action'
author: Arnob Almazee
description: DigitalOcean kubectl image Update by using Github Action
branding:
  color: 'blue'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/arn-ob/do-kubectl-action:latest'
inputs:
  do_access_token:
    description: Access token for accessing the doctl. 
    required: true
  do_cluster_certificate:
    description: Cluster certificate for accessing the kubectl. 
    required: true
  do_deployment_name:
    description: App deployment name. 
    required: true
  do_container_name:
    description: App container name. 
    required: true
  do_image_tag:
    description: App build image and tag. 
    required: true
  do_namespace:
    description: Deployment Namespace
    required: false
  stdin:
    description: File to read and pass as stdin to kubectl
    required: false
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: false
outputs:
  kubectl-out:
    description: The output of the kubectl command 
